import {
  Activity,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Calculator,
  Camera,
  Coffee,
  Coins,
  Droplets,
  Dumbbell,
  Feather,
  Flame,
  Footprints,
  GraduationCap,
  Heart,
  Languages,
  Layers,
  Lightbulb,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Palette,
  PenLine,
  PersonStanding,
  PhoneOff,
  PiggyBank,
  Receipt,
  Rocket,
  Salad,
  ShoppingBag,
  Sigma,
  Sparkles,
  Star,
  Sun,
  Target,
  TrendingUp,
  Wallet,
  Wind,
} from "lucide-react";

export const HABIT_ICONS = {
  dumbbell: Dumbbell,
  footprints: Footprints,
  activity: Activity,
  person: PersonStanding,
  flame: Flame,
  bike: Bike,
  mountain: Mountain,
  heart: Heart,
  graduation: GraduationCap,
  book: BookOpen,
  sigma: Sigma,
  languages: Languages,
  layers: Layers,
  calculator: Calculator,
  lightbulb: Lightbulb,
  target: Target,
  receipt: Receipt,
  piggy: PiggyBank,
  trending: TrendingUp,
  rocket: Rocket,
  bag: ShoppingBag,
  wallet: Wallet,
  briefcase: Briefcase,
  coins: Coins,
  wind: Wind,
  moon: Moon,
  notebook: NotebookPen,
  droplets: Droplets,
  phoneoff: PhoneOff,
  salad: Salad,
  coffee: Coffee,
  sun: Sun,
  brush: Brush,
  music: Music,
  feather: Feather,
  camera: Camera,
  palette: Palette,
  pen: PenLine,
  star: Star,
  sparkles: Sparkles,
  brain: Brain,
};

export const iconFor = (key) => HABIT_ICONS[key] || Target;
